### ISSUE TITLE
clean this up

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genomicscourse#108]
1. name columns right away and use names for subsetting

<img width="1054" alt="Screenshot 2022-10-03 at 16 15 31" src="https://user-images.githubusercontent.com/150113/193613580-8d09e845-9cb8-4eb0-8fe8-f3eff52900c4.png">

2. Use named arguments in functions . 2 examples here, but applies everywhere: 
<img width="984" alt="Screenshot 2022-10-03 at 16 16 30" src="https://user-images.githubusercontent.com/150113/193613766-119a8143-324a-4535-acd3-9583113f67da.png">
<img width="1142" alt="Screenshot 2022-10-03 at 16 17 29" src="https://user-images.githubusercontent.com/150113/193613909-0963dba6-224e-4327-b41c-08053c8fef2c.png">
<img width="532" alt="Screenshot 2022-10-03 at 16 21 18" src="https://user-images.githubusercontent.com/150113/193614791-d937c841-9195-47f4-8e39-1df55c001732.png">

3. ugly  :
<img width="951" alt="Screenshot 2022-10-03 at 16 19 23" src="https://user-images.githubusercontent.com/150113/193614408-2ef16673-9063-4d49-8f43-bcf8e5b6f2c3.png">

4. use .vcf extention (unless the software is completely retarted)
<img width="1006" alt="Screenshot 2022-10-03 at 16 20 28" src="https://user-images.githubusercontent.com/150113/193614647-2b004405-eeed-49a4-ae64-a539dc00a05b.png">

**Comment by MPriebe** [comment]
1-3 have been addressed by @gabrielluishernandez and myself. 4 will have to wait until after the practicals are run because we don't have time
