### ISSUE TITLE
Practical gene prediction 

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genomicscourse#117]
'# Link this scaffolds file into your input directory
ln -s ../../../../data/backup_assembly/scaffolds.fasta ."

Should be an absolute link instead /shared/data....

**Comment by yannickwurm** [comment]
" a simple scenarion. " 

 -> scenario

**Comment by yannickwurm** [comment]
"(remember to add 1 at the end; this provides hints to Augustus about the gene structure based on what we know from honeybee)."
 --> "on what we know about gene composition from honeybee"

**Comment by yannickwurm** [comment]
"We will compare them using BLAST to known sequences from other species in the [uniref50 database](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4375400/).

2.1 Running BLAST with SequenceServer

We will use [SequenceServer](https://sequenceserver.com/) to run BLAST."


Here at the beginning, please remove "in the uniref50 databases". 

At the end, say against the Swissprot database (faster), or the Uniref50 database (slower)

**Comment by AlexisGGk** [comment]
Changes were made
