### ISSUE TITLE
2017

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genomicscourse#2]
This is all relative to this years course. e.g. https://github.com/wurmlab/genomicscourse/blob/master/2017/practicals/reference_genome/assembly.md

@adrlar  can we suppose that everyone will have the data dir locally (on PC or VDI) in `~/2017-09-BIO721_genome_bioinformatics_input` (this directory should be read-only)? Or is there a single (different) path that we can point them to (and ask them to create a link to that home dir?)  
- [x] Get the data subsection - needs to be revised according to @adrlar 's response

- [x] Modify all directory dates (e.g. `2016-10-03-whatever`) to their corresponding 2017 version. (Note that day of week also changes!)
- [x] directory `-reference` is -reference_genome` (change everywhere)
- [ ] ~~is there a more elegant way to the kmer filtering part of  L125-145 (line nums may shift) with kmc2? (rather than messy khmer)  (ideally without interleaving/uninterleaving)~~ [see comment below]
 - [x] if sequenceserver is already installed, they don't need to do it (and the text needs to be correspondibly revised
 - [x] if the reference db is already downloaded and blast formatted, they don't need to do it.  (L252, "Quality control of individual genes"
 - [x] split into 2 files (one for cleaning, another for assembly)

---

- [x] Changes made to `2017/data/reference_databases` (commit 92462e7c) needs to be synced to `/data/SBCS-MSc-BioInf`
- [ ] ~~Regenerate website once open PRs (currently #10) have been merged~~ (my bad, website is automatically built when pushed to master)

**Comment by yeban** [comment]
@yannickwurm wrote:

> is there a more elegant way to the kmer filtering part of L125-145 (line nums may shift) with kmc2? (rather than messy khmer) (ideally without interleaving/uninterleaving)

kmc is faster and probably a little more straightforward (count k-mers, then eliminate low and high coverage). However, kmc also generates orphans and interleaving and deinterleaving the reads would be required to eliminate orphans using seqtk in step 4.

**Comment by yannickwurm** [comment]
mmm 
are you sure that seqtk needs the manual interleaving for this?
a separate interleaving/deinterleaving step may be simpler to understand (or grep identifiers from both files;  uniq -d; seqtk subseq). But it is not essential to change this. Much more important is that things run smoothly (see also my comment on your software PR)

**Comment by adrlar** [comment]
Found out yesterday afternoon that the underlying filesystem for the networked mount does not support symlinks. 

all ln -s commands have to be changed into cp unfortunately.

**Comment by yannickwurm** [comment]
@yeban can you resolve these last issues? Thanks, y

**Comment by yeban** [comment]
@yannickwurm #11 resolves the last issue related to data subsection. I am not quite sure what you mean by "split into 2 files (one for cleaning, another for assembly)"

**Comment by yeban** [comment]
Only @roddypr has the permission to write to `/data/SBCS-MSc-BioInf/data`, thus I am unable to:

1. Symlink `DO_WHILE_BUILDING_IMAGE` to `download_reference_databases` (commit: 92462e7)
2. Run the script to pre-download the database
