### ISSUE TITLE
popgenome etc in R

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genomicscourse#21]
Several issues:
 - Naming conventions too minimalistic
 - two PCAs (doing this once is sufficiently confusing)
 - graphs often lack labels.

**Comment by yeban** [comment]
@MPriebe Do your modifications to practical 5 address the issues raised above? If not, what remains.

**Comment by yeban** [comment]
I believe @aswitwicka's changes (#68) addresses the issues raised here.
