### ISSUE TITLE
2019 - basic updates starting with read cleaning practical

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#23]
1. "Locate input data to work with" section in read cleaning practical needs to be updated. The data are available on local PC at `/import/teaching/bio/data`. Here, we want them to symlink to the data instead of making a copy.

2. Subsequent section "Set up directory hierarchy to work in" starts by saying 'All work must be done in `~/apocrita`. This is no longer the case. We will want them to create their base dirs in home directory.

3. As per point 2 above, `~/apocrita` needs to be removed from the paths throughout.

4. Related to 3, we need to change 2018 to 2019 throughout. Here, it might be worth considering dropping the day component of date throughout (i.e., 2019-09 instead of 2019-09-28). The argument in favour of keeing it is that we want to teach them the "right" pattern (full date). However, there's a recurring cost every year (even if a few minutes) to update this. Alternative idea is to change it to xx (i.e, 2019-09-xx). This is because we anyway don't know the exact date until a few days before the practical and in the practical we anyway ask them to change the day to today's date.

**Comment by yannickwurm** [comment]
Go for 2019-09-xx

**Comment by ivopieniak** [comment]
@yeban Please review the pull request for the changes so I can proceed with the rest.

**Comment by yeban** [comment]
For the issue to be closed, point 3 & 4 need to be addressed in variant calling practical (`practicals/population_genetics/map_call.md`)

**Comment by yeban** [comment]
This is addressed I believe
