### ISSUE TITLE
2019 - MAKER

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#25]
MAKER caused problems last time. I don't remember exactly why, but I guess it was because practical asks them to run it on Apocrita but we ended up asking them to run on local PC afterwards.

- Check MAKER can be run on local PC and update practicals accordingly.
- Need to be extra vigilant because installation is being outsourced and we don't what version we might end up with.

**Comment by ivopieniak** [comment]
Per Tom's King message 
"Looking at the complexity of the build this morning, I can’t guarantee it unfortunately as it requires pulling in a large perl dependency list which is hard to maintain" 

I used scp to copy the fasta file on the apocrita and ran Maker which did the job rapidly and without any issues.

**Comment by ivopieniak** [comment]
I have recieved a following message from Tom King: 
"Looking at the complexity of the build this morning, I can’t guarantee it unfortunately as it requires pulling in a large perl dependency list which is hard to maintain."

I found maker on a local computer but it is not installed correctly per the error messages. 

Running maker on the cluster did not cause any problems and was very rapid.

**Comment by yeban** [comment]
I have provided a MAKER singularity container but it has not been deployed (yet).

To close this issue:
- [ ] maker.simg needs to be added to `/import/teaching/bio`
- [ ] `alias maker="singularity run /import/teaching/bio/maker.simg` needs to be added to `/import/teaching/bio/biotools.sh`
