### ISSUE TITLE
2019 - FASTQC 0.11.8 

### ISSUE THREAD

**Issue by ivopieniak** [wurmlab/genomicscourse#27]
FastQC runs the analysis, however it cannot save/create HTML report, thus the default .zip output is corrupted and useless. 

Error message:
'Failed to create an archive: can't create the output stream'

This was mentioned in this thread, however providing explicit paths to the files for limitations and adapters did not help.
https://www.biostars.org/p/189261/

Suggestion is to use older version - 0.11.7 and not 0.11.8.

**Comment by yeban** [comment]
Since the issue is closed, can we take that to mean that the correct version of FASTQC (i.e., 0.11.7) has been installed?

**Comment by ivopieniak** [comment]
The issue with the FASTQC 0.11.8 was associated with no permissions to create tmp files by fastqc in the /tmp directory. Guys fixed it up last week, but Tom King has managed to install the fastqc 0.11.7 anyway in the meantine. Overall, both versions work just fine now, thus i closed this issue.
