### ISSUE TITLE
Issues with 2019 practical

### ISSUE THREAD

**Issue by ivopieniak** [wurmlab/genomicscourse#28]
- [x] Maker works nomrally only on the Apocrita - requirement of copying the files back and forth to do gene prediction. 
- [x] Could not localise singularity containers with seqserv and genevalidator nor blast, thus could not do quality control step.
- [x] KHMER is not installed - KMC is there instead @yeban 
- [x] There is no parallel installed locally.

**Comment by yeban** [comment]
> There is no parallel installed locally.

Push them to get it installed. It is required for the read mapping practical.

**Comment by ivopieniak** [comment]
Tom is doing right now

**Comment by yeban** [comment]
@ivopieniak 

> Could not localise singularity containers with seqserv and genevalidator nor blast, thus could not do quality control step.

What's the status on this?

**Comment by ivopieniak** [comment]
It's done.
