### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#30]
I modified read ids so that read cleaning practical is less convoluted.

- [x] Need to copy `/data/SBCS-MSc-BioInf/2019p/reads.*.fastq.gz` to `/import/teaching/bio/data` (@ivopieniak)
- [x] Need to go over the changes to read cleaning practical and stuff in /data/SBCS-MSc-BioInf with Yannick

**Comment by ivopieniak** [comment]
@yeban I cannot copy the files from apocrita since I have no permissions.

**Comment by yeban** [comment]
Please ask Tom (we need this done today so that Gabriel can start testing tomorrow).

**Comment by yeban** [comment]
This is done.
