### ISSUE TITLE
2019 - source /import/teaching/bio/biotools.sh

### ISSUE THREAD

**Issue by ivopieniak** [wurmlab/genomicscourse#34]
Students are currently expected to `source /import/teaching/bio/biotools.sh` themselves for the tools to be available.

Push Tom to have this added to their bash_profile or so automatically.

**Comment by yeban** [comment]
I have added the following to the read cleaning practical, just in case:

![Screenshot 2019-09-24 at 11 39 01](https://user-images.githubusercontent.com/90373/65504910-ec888300-debf-11e9-9d6b-488784d7ca4d.png)

To make sure no PC has a problem we can run `seqtk` on all PCs (maybe after class today evening or during lunch) and report numbers of the PC where it didn't work to Tom and his team.

**Comment by yeban** [comment]
> To make sure no PC has a problem we can run seqtk on all PCs (maybe after class today evening or during lunch) and report numbers of the PC where it didn't work to Tom and his team.

It has become clear from the classes being held today that `source biotools.sh` is already included in .bash_profile for 85% of the students.

@ivopieniak Please could you close this issue once you are convinced that `source biotools.sh` works for all of them.
