### ISSUE TITLE
2019 - potentially set an alias to open HTML files

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#38]
It would be nice if we can have students double click on FastQC's HTML report instead of opening it from the terminal:

- ~~Test if `gio open .` works (i.e., it opens a file explorer list contents of the current directory)~~
- ~~If yes, get the following alias deployed to biotools.sh: `alias open="gio open"`~~
- ~~Update practical~~

**Comment by yannickwurm** [comment]
disagree - we want them to avoid the GUI wherever possible

gio open thing.html would be cool though

**Comment by yeban** [comment]
Okay. I can confirm that `gio open thing.html` worked when I tested the PCs on Friday. But it opened the file in Chrome. So revised TODO:

- [ ] Figure out way to open the HTML file in Firefox using `gio open`. Options: make sure Firefox is the default browser. Otherwise there should be a way to pass application to `gio open` (e.g., `gio open -a Firefox ...`)
- [ ] If this requires setting up an alias, get the alias deployed.
- [ ] Update practical

**Comment by yeban** [comment]
`gio open` itself does not take any options. It will open the given file in the default application associated with that filetype.

For `gio open` to open the given HTML file in Firefox, Firefox will need to be set as the default browser. Seems unlikely to me that Tom and his team will want to make that happen. Anyway, between `gio open foo.html` and `firefox foo.html` I don't see any reason to prefer the former.

I am thus closing this issue.
