### ISSUE TITLE
2019 - bgzip command is not installed

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#43]
Required for practical 5

@ivopieniak Please can you talk to Tom/Keith/Harry/Alijandro (whoever) and get this done asap

**Comment by ivopieniak** [comment]
It should be available soon. Tom installed it and students just need to log out and log in. Issue solved.

**Comment by yeban** [comment]
Are you in the room and able to confirm that bgzip command works after logging out and logging in?

**Comment by yeban** [comment]
Sorted. Thanks!
