### ISSUE TITLE
SOAPdenovo

### ISSUE THREAD

**Issue by ivopieniak** [wurmlab/genomicscourse#45]
There is a potential issue that can arise based on the experience with BWA - since SOAP is ram intense, there is a chance that the server may crash when all the students would decide to run SOAP at the same time. I have spoken with EECS and they said that it is very likely to happen since the server and the NFS was not designed to handle this kind of biological software. @yeban @yannickwurm

**Comment by yannickwurm** [comment]
Don't understand the link. 

The dataset isn't that big. 

Can you test later today running simultanously on 5-10 machines?  I suspect students will be somewhat staggered....

**Comment by yeban** [comment]
This didn't prove to be a problem for us
