### ISSUE TITLE
singularities

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genomicscourse#58]
Hi Priyam,
can you please add here the singularity def files that were needed?
Thanks,
Yannick

**Comment by yeban** [comment]
The def files (recipes), images, and instructions for building more singularity images are here `/data/SBCS-MSc-BioInf/2019-priyam_singularity_images`. I have indicated this in `2019/software.md` as well.

For your reference these are:

```
/data/SBCS-MSc-BioInf/2019-priyam_singularity_images
├── maker-2.31.10.tgz
├── maker.recipe
├── maker.simg
├── README
├── rstudio.recipe
├── rstudio.simg
├── sequenceserver.recipe
└── sequenceserver.simg
```

**Comment by yeban** [comment]
Just to be clear, it's here:

https://github.com/wurmlab/genomicscourse/tree/master/2019/singularity
