### ISSUE TITLE
Update website link in repo to 2020 version

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#59]
The highligted link in the screenshot below:

<img width="1231" alt="Screenshot 2020-07-27 at 09 52 07" src="https://user-images.githubusercontent.com/90373/88522880-f2bf2280-cfee-11ea-995e-22fb7de0f86c.png">

to: http://wurmlab.github.io/genomicscourse/2020/practicals/

**Comment by yannickwurm** [comment]
changed
