### ISSUE TITLE
readData fails in popgen practical

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#61]
[`readData` function in the popgen practical](https://github.com/wurmlab/genomicscourse/blob/master/2020/practicals/population_genetics/popgen.Rmd#L173) fails on the new setup with the following error:

```
|            :            |            :            | 100 %
|==========================Error in setwd(dfile) : cannot change working directory
```

I have tried passing `./popgenome-vcf` as well as absolute path to the function. I also tried moving the VCFs and passing `.` to the function. None worked.

**Comment by yeban** [comment]
Also, it is possible to issue `setwd` in the R console, so it is not a limitation of Rstudio server.

**Comment by yeban** [comment]
This turned out to be a problem only for the default `ubuntu` user.

**Comment by yannickwurm** [comment]
ok - note that we should never use setwd in a script. 
instead we should open the script in the right place so that Rstudio automatically knows the right wd

**Comment by yeban** [comment]
The setwd in this case is in the readData function of PopGenome package.
