### ISSUE TITLE
samtools view is not required before samtools sort (practical 4)

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#62]
It is no longer required to pass SAM output from read mappers through `samtools view -b`. Instead, `-o BAM` can be specified directly to `samtools sort`.

**Comment by yannickwurm** [comment]
we should indeed implement these kinds of simplifications/updates


On 2020Aug3, at 13:53, Anurag Priyam <notifications@github.com<mailto:notifications@github.com>> wrote:



It is no longer required to pass SAM output from read mappers through samtools view -b. Instead, -o BAM can be specified directly to samtools sort.
