### ISSUE TITLE
GeneValidator (practical 3)

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#65]
@yannickwurm headsup / question:

I also installed GV on the server running SequenceServer. So it would be possible for the students to run GV this time instead of only viewing the screenshots. I updated the practical to tell them to try the same example with GV as they would with SequenceServer/BLAST in the previous section.

Is this okay or should I revert this section to only show them the screenshots? If this is okay, then we need to go better prepared to answer GV related question.

**Comment by yeban** [comment]
Judging from #18 we did have a running GV server once but perhaps switched to showing screenshots because of database and computational constraints.

Based on Guy's feedback the change back to a running GV server this year is a success.

**Comment by yannickwurm** [comment]
THanks - In general, its always better to have the students perform the actual analysis
