### ISSUE TITLE
Practical 4 overuses inline code blocks

### ISSUE THREAD

**Issue by yeban** [wurmlab/genomicscourse#74]
All mentions of software are enclosed in a backtick causing it to be rendered in typewriter font. Most published work (papers, books), as well as practicals 1 to 3 do not use typewriter font when calling out software by name.

For e.g.,

correct: we will use bowtie2
incorrect: we will use `bowtie2`

**Comment by paoloinglese** [comment]
Fixed. Now only the commands follow the right style, while the programs are in italic.
