### ISSUE TITLE
prac 1

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genomicscourse#77]
- [x] add that  "emerging model organisms" includes most crops, most animal & plant pest species, many pathogens, and most major models for ecology & evolution.
- [x] add "Do not jump ahead". 
- [x] ther tools including fastx_toolkit, kmc2 and Trimmomatic can also be useful.  ** but we won't use them now**    also kmc2 is irrelevant giv en kmc3
-  [x] o appropriately trim from the beginning (--cut) and end (--quality-cutoff) of the sequences 
       to identify a relevant quality cutoff, you'll need to read the cutadapt documentation, understand phred scores, and examine your fasqtc qualiyut scores

- [x] Say you have sequenced your sample at 45x genome coverage.  ** THis means that every nucleotide of the genome was sequenced 45 times on average... so for a genome of 450,000,000 nucleotides, this means you have  xxxxxxxxx nucleotides of raw sequence. 

- [ [ The real coverage distribution will be influenced by factors including DNA quality, library preparation type and local GC content, but you might expect most of the genome to be covered between 20 and 70x    --> sentence too long. chop in 2. 
- [x] Below, we use kmc3 to "mask" extremely rare k-mers (i.e., convert each base of rare k-mers to 'N'). **This is because we know that those portions of sequences are not really present in the species**

**Comment by yeban** [comment]
done
