### ISSUE TITLE
Initial Testing

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genomicscourse#84]
@gabrielluishernandez  the entire process that the students do wants to be tested
 - [ ] e.g., student sits down in front of machine. Logs in. Then goes to the unix bootcamp page. 
 - [ ] e.g., Switches on their virtual machine through the James web interface. SSH to the server. 
   So you need to coordinate with @james-milburn-crowe to ensure that the machines are launchable, and that he's created a machine that you'll be able to launch.

@James: 
 - [ ] the genomicscourse unix bootcamp and VM access needs to be running so Gabriel can test it. 
 - [ ] the students each need their own virtual machine, that they can  launch. - please coordinate with admin (probably Natalie?) to ensure you have their names/emails/ids

# @gabrielluishernandez content reorganising on the QMPlus page

page for bio721p  is here 
 https://qmplus.qmul.ac.uk/course/view.php?id=6443
   At the top right is an "edit" button

It needs the following changes:
 - [x]  reorder the days so they match the order here (you should be able to move the entire block of a day). E.g., 
  https://docs.google.com/spreadsheets/d/1cdqsukZUER-DWvRKc-TnZd0oP8KvRx7ZmeLyqQsqaY4/edit?usp=sharing
 - [x] rename the days for 2021 (ha!). But lets do this in a manner that requires fewer edits in the future. Currently the title is "Monday 21st" - instead of making it Monday 27th, make it "Week 1: Monday", and the subsequent one "Week 2: Monday"
 - [x] make recordings of crappy zoom discussions invisible to the students
 - [x] hide the current "general discussion" forum (make it invisible to students). Create a new one. 
 - [x] change the links for all of the sections to 2021 (from 2020).     Eg there may be links to https://wurmlab.com/genomicscourse/2020/docs/ssh or to specific practicals - the link needs to point to the 2021 version

Please take note of anything that is ambiguous, or should be improved. Open issues here on GitHub as appropriate. In a second phase we'll want to (with help from Alicja and others), revise the practicals for flow and consistency

Thanks very much for your help with all this

**Comment by gabrielluishernandez** [comment]
@yannickwurm ,
Some of the activities at QM-plus have times specification (e.g 11 am Introduction to Unix).
Do we want to completely delete the specifications for flexibility or, try to adapt them to this year's schedule?

**Comment by gabrielluishernandez** [comment]
- [ ] Zoom links are not valid 
- [ ] Command line bootcamp link not found (sep 8,2021)
- [ ] At Week 1, Tuesday. Is the comment still relevant in activity: "Self-guided tutorial - Using SSH to connect to your unix machine"
- [ ] Week 2, Thursday. Broken link to video: "General context & our research (45 mins; vimeo)"
- [ ]

**Comment by yannickwurm** [comment]
Yannick Wurm is inviting you to a scheduled Zoom meeting.

Topic: Bio721p Genome Bioinformatics
Time: This is a recurring meeting Meet anytime

Join Zoom Meeting
https://qmul-ac-uk.zoom.us/j/7326486386?pwd=cklhV3c0R1Z5WXRDNldMU2dlWHVrQT09

Meeting ID: 732 648 6386
Passcode: alun
One tap mobile
+442080806592,,7326486386#,,,,*028923# United Kingdom
+443300885830,,7326486386#,,,,*028923# United Kingdom

Dial by your location
        +44 208 080 6592 United Kingdom
        +44 330 088 5830 United Kingdom
        +44 131 460 1196 United Kingdom
        +44 203 481 5237 United Kingdom
        +44 203 481 5240 United Kingdom
        +44 203 901 7895 United Kingdom
        +44 208 080 6591 United Kingdom
        +1 646 558 8656 US (New York)
        +1 669 900 9128 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
Meeting ID: 732 648 6386
Passcode: 028923
Find your local number: https://qmul-ac-uk.zoom.us/u/kcKBKljlFT

Join by SIP
7326486386@zoomcrc.com

Join by H.323
162.255.37.11 (US West)
162.255.36.11 (US East)
115.114.131.7 (India Mumbai)
115.114.115.7 (India Hyderabad)
213.19.144.110 (Amsterdam Netherlands)
213.244.140.110 (Germany)
103.122.166.55 (Australia Sydney)
103.122.167.55 (Australia Melbourne)
149.137.40.110 (Singapore)
64.211.144.160 (Brazil)
149.137.68.253 (Mexico)
69.174.57.160 (Canada Toronto)
65.39.152.160 (Canada Vancouver)
207.226.132.110 (Japan Tokyo)
149.137.24.110 (Japan Osaka)
Meeting ID: 732 648 6386
Passcode: 028923

**Comment by yannickwurm** [comment]
zoom - see my email
for morning activities - please add a blurb towards the top of the page indicating that "Mornings are asynchronous, thus indicated timings are suggestions". Afternoons are synchronous in person activities (for everyone who can make it to room Queens E223).

**Comment by yannickwurm** [comment]
- [ ] machines automatically shutting down in 10 minutes @james-milburn-crowe 
- [ ] create vm for each of the assistants @james-milburn-crowe 
- [ ] Gabriel check that command line bootcamp links works when James has switched it on
- [ ]

**Comment by yannickwurm** [comment]
Joanna Bullimore <joanna.bullimore@qmul.ac.uk> says "The lab has had the machines physically installed but the building (applying the OS and apps) is due to take place this week, so over the next couple of days. As soon as we have at least a few machines built, then I’ll get in touch and let you know. I’m hoping for Monday, so at a minimum I’ll update you then."

**Comment by yannickwurm** [comment]
Joanna says "The lab has now been more or less had all the machines built and is available for any testing you’d like to do this week.
Please do let me know when you’d like to visit and we can have someone meet you to take you up to the room – likely to be either myself or my colleague Iqbal who is managing the project of fitting out the room." - please get in touch with her

**Comment by yannickwurm** [comment]
I think a bunch of these are resolved - @gabrielluishernandez @james-milburn-crowe  please tick all the boxes, and highlight if anything is remaining. or obviously close the overall thing if all is resolved
