### ISSUE TITLE
Bootcamp comments

### ISSUE THREAD

**Issue by gabrielluishernandez** [wurmlab/genomicscourse#87]
Dear @james-milburn-crowe, here are my comments:

- [ ] Section 11: Man pages. Suggested command `man cd` has output `No manual entry for cd`. I don't know if this is expected or should be fixed.
- [ ] Section 14: Creating empty files with the touch command. The hyperlink in `touch`  is wrong (it takes you to "wiki Command-line completion" instead)
- [ ] Section 15: Moving files. The hyperlink in `mv` takes you to the "it may refer to:" page rather than to the relevant page.
- [ ] Section 15: Moving files. The introduction to wild-card characters is a bit random and thus, I think it may be confusing for the student to be introduced to such an important topic in this manner. (just my opinion) 

Also, I agree with Priyam and Marian on their previous comments. Cheers

**Comment by yannickwurm** [comment]
@james-milburn-crowe - where is the code for this?

**Comment by yannickwurm** [comment]
- [ ] @james-milburn-crowe please make a new repo for the cli bootcamp

**Comment by RaphaellaJackson** [comment]
As of Tuesday 21st September:
- Section 11: '''man cd''' problem reported by Gabriel is still present
- Section 5: students may be inclined to run the '''mkdir -p inner/outer''' command that is described, if they do this will cause problems when they try to delete the directory in lesson 12 as it will not be empty. 
- Section 26: '''echo $USER''' returns nothing
- Section 27: '''less testfile.vcf''' this command does not work and I'm not sure what file it's supposed to be referring to, I'm guessing this is an artifact of an earlier version.

**Comment by james-milburn-crowe** [comment]
Section 5 - good catch - I'll work out what to do with that - maybe introduce them to rm -rvf  :D :D

Section 11 - man page issue - fixed

Section 14 - fixed, need to redeploy

Section 15 - fixed, need to redeploy

Section 26: 

Section 27 - this should be grades.txt rather than testfile.vcf - fixed on next restart

**Comment by yannickwurm** [comment]
Hi guys, are these resolved?

**Comment by james-milburn-crowe** [comment]
running a little close to the wire, but these hadn't deployed - they have now, and I've just tested - section 5 is a bit of a bodge - adding in the full path makes the eg command work only if they didn't run it already

**Comment by james-milburn-crowe** [comment]
I still can't close stuff though, but this issue can be closed
