### ISSUE TITLE
-- should add a step to say delete your .sam files!  (or entire tmp folders)

### ISSUE THREAD

**Issue by gabrielluishernandez** [wurmlab/genomicscourse#88]

**Comment by gabrielluishernandez** [comment]
did it like this:
Once you are sure the files are in `results`, clean the `tmp` directory.

```bash
rm -ri tmp
```

**Comment by yannickwurm** [comment]
Next time please reference your commit

**Comment by yannickwurm** [comment]
4f9afd6bbd8d8359e81b56627105a690c0f637e1

and if you've addressed an issue, just close
