### ISSUE TITLE
more informative messages

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genomicscourse#89]
https://switch.genomicscourse.com/?response=true

should show the actual server hostname / and potentially command?

**Comment by yannickwurm** [comment]
(is there a newer snapshot that includes the 3 buttons (one for R, one for ~www)?

- [ ] tell users to wait 30 seconds before ssh-ing to allow the machine to start up.

**Comment by james-milburn-crowe** [comment]
Github doesn't seem to have a newer version of the ruby app that runs this, nor does the AMI on amazon. It's not a complicated app though, can you outline the functionality it needs, so I'm clear before I make the changes?

**Comment by yannickwurm** [comment]
Hi James,
as outlined the other day:
 - explicit ssh command
 -  link to ~www (or ~www/tmp)
 -  link to that machine's Studio
