### ISSUE TITLE
*** System restart required ***

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/genomicscourse#90]
Is one of the first messages displayed to users & shouldn't be. 

ybp ➜  ~ ssh btw586@btw586.genomicscourse.com 
The authenticity of host 'btw586.genomicscourse.com (3.13.233.92)' can't be established.
ECDSA key fingerprint is SHA256:qkKVvYyz8zNDJcniGLIPozauGus31FBss/UF4HKHvOM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'btw586.genomicscourse.com,3.13.233.92' (ECDSA) to the list of known hosts.
btw586@btw586.genomicscourse.com's password: 
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 5.4.0-1025-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Sep 17 13:16:05 UTC 2021

  System load:  0.08               Processes:           114
  Usage of /:   60.5% of 29.02GB   Users logged in:     0
  Memory usage: 9%                 IP address for eth0: 172.31.20.191
  Swap usage:   0%

 * Ubuntu Pro delivers the most comprehensive open source security and
   compliance features.

   https://ubuntu.com/aws/pro

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

81 packages can be updated.
1 update is a security update.

New release '20.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

*** System restart required ***

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

**Comment by james-milburn-crowe** [comment]
Will be taking these down later today for a restart to fix this, then building a new AMI off the image

**Comment by yannickwurm** [comment]
Hi @james-milburn-crowe - if this is done please close
