### ISSUE TITLE
SPAdes didn't work

### ISSUE THREAD

**Issue by gabrielluishernandez** [wurmlab/genomicscourse#93]
Hello @james-milburn-crowe 
I have run into this error while using spades in "part2: genome assembly" practical. I entered the following command:

`spades.py -o tmp -1 input/reads.pe1.clean.fq -2 input/reads.pe2.clean.fq`

After a few minutes it returned the following and did not create the `fasta` file:

`== Error ==  system call for: "['/shared/conda/envs/spades/bin/spades-core', '/shared/home/btx645/2021-09-22-assembly/tmp/K33/configs/config.info']" finished abnormally, OS return value: 255`

Cheers

**Comment by RaphaellaJackson** [comment]
I have experienced the identical issue with the same error message. Seems to be a memory allocation issue, see end of log output below: 

Command entered:
spades.py -o tmp -1 input/reads.pe1.clean.fq -2 input/reads.pe2.clean.fq

Log From Right before it died: 

  0:00:00.053     4M / 11M   INFO    General                 (kmer_splitters.hpp        :  97)   Using cell size of 8387114
  0:00:08.619     2G / 2G    INFO    General                 (kmer_splitters.hpp        : 287)   Processed 1331909 reads
  0:00:08.960     2G / 2G    INFO    General                 (kmer_splitters.hpp        : 287)   Processed 1335418 reads
  0:00:09.007    16M / 2G    INFO    General                 (kmer_splitters.hpp        : 293)   Used 1335418 reads
  0:00:09.007    16M / 2G    INFO    General                 (kmer_index_builder.hpp    : 120)   Starting k-mer counting.
  0:00:09.009    16M / 2G    ERROR   General                 (mmapped_reader.hpp        :  52)   mmap(2) failed. Reason: Cannot allocate memory. Error code: 12


== Error ==  system call for: "['/shared/conda/envs/spades/bin/spades-core', '/shared/home/btx452/2021-09-22-assembly/tmp/K33/configs/config.info']" finished abnormally, OS return value: 255

**Comment by james-milburn-crowe** [comment]
I'd just been looking into this, got the same error - this is to be expected, as we're running with smaller images than the assemblies would be run on - spades takes a large memory footprint. I'm going to mark this as closed, with this as a note - change image size to large when running assembly practical

**Comment by yannickwurm** [comment]
Hi guys, can you confirm please that this runs with the larger machines?  As it could also be a software compatibility issue

**Comment by yannickwurm** [comment]
Is this resolved?

**Comment by gabrielluishernandez** [comment]
It ran yesterday properly
