### ISSUE TITLE
Student Log In Issues

### ISSUE THREAD

**Issue by RaphaellaJackson** [wurmlab/genomicscourse#97]
Student hmy575 cannot log in via 
`ssh hmy575@hmy575.genomicscourse.com`
but can log in via
`ssh hmy575@18.190.4.52`

**Comment by yannickwurm** [comment]
@paoloinglese  - Natalie should be able to tell you which room we'll be in & It would be great to test this before
(and perhaps in the switch output, *also* show the elastic IP)
